executable = wordcount.py 
arguments = 

transfer_input_files = 

should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT

log           = logs/job.$(Cluster).$(Process).log
error         = logs/job.$(Cluster).$(Process).err
output        = logs/job.$(Cluster).$(Process).out

+JobDurationCategory = "Medium"

request_cpus   = 1
request_memory = 100MB
request_disk   = 100MB

queue
